DROP TABLE IF EXISTS PROJECT;

DROP TABLE IF EXISTS SPRINT;

DROP TABLE IF EXISTS TASK;

DROP TABLE IF EXISTS USER;

DROP TABLE IF EXISTS USERSTORY;

CREATE TABLE PROJECT
(
   IDPROJECT            INT NOT NULL,
   IDUSER               INT NOT NULL,
   NAME                 VARCHAR(254),
   DISCRIPTIO           VARCHAR(254),
   PRIMARY KEY (IDPROJECT),
   KEY AK_IDENTIFIANT_1 (IDPROJECT)
);

CREATE TABLE SPRINT
(
   IDSPRINT             INT NOT NULL,
   NUMERO               INT,
   DATEDEBUT            DATETIME,
   DATEFIN              DATETIME,
   PRIMARY KEY (IDSPRINT),
   KEY AK_IDENTIFIANT_1 (IDSPRINT)
);

CREATE TABLE TASK
(
   IDTASK               INT NOT NULL,
   IDSPRINT             INT NOT NULL,
   DISCRIPTION          INT,
   ETAT                 INT,
   PRIMARY KEY (IDTASK),
   KEY AK_IDENTIFIANT_1 (IDTASK)
);

CREATE TABLE USER
(
   IDUSER               INT NOT NULL,
   MAIL                 VARCHAR(254),
   PASSWORD             VARCHAR(254),
   REGISTRATIONDATE     DATETIME,
   PRIMARY KEY (IDUSER),
   KEY AK_IDENTIFIANT_1 (IDUSER),
   KEY AK_IDENTIFIANT_2 (IDUSER)
);

CREATE TABLE USERSTORY
(
   IDUSERSTORY          INT NOT NULL,
   IDPROJECT            INT NOT NULL,
   IDSPRINT             INT NOT NULL,
   DISCRIPTION          VARCHAR(254),
   PRIORITY             INT,
   COST                 INT,
   ETAT                 INT,
   PRIMARY KEY (IDUSERSTORY),
   KEY AK_IDENTIFIANT_1 (IDUSERSTORY)
);

ALTER TABLE PROJECT ADD CONSTRAINT FK_ASSOCIATIONUSERPROJECT FOREIGN KEY (IDUSER)
      REFERENCES USER (IDUSER) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TASK ADD CONSTRAINT FK_ASSOCIATIONTASKUSERSTORY FOREIGN KEY (IDSPRINT)
      REFERENCES SPRINT (IDSPRINT) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE USERSTORY ADD CONSTRAINT FK_ASSOCIATIONPROJETUSERSTORY FOREIGN KEY (IDPROJECT)
      REFERENCES PROJECT (IDPROJECT) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE USERSTORY ADD CONSTRAINT FK_ASSOCIATIONUSERSTORYSPRINT FOREIGN KEY (IDSPRINT)
      REFERENCES SPRINT (IDSPRINT) ON DELETE RESTRICT ON UPDATE RESTRICT;

